--- 
document: 
  description: "Lo scopo del documento è quello di fornire ai soggetti aderenti all’iniziativa tutte le indicazioni utili e le regole da attuare per implementare i pagamenti elettronici verso la PA."
  name: "PagoPA Overview"
  tags: 
    - pagoPA
